In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'2.3.1'

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [5]:
 df.shape[0]

9704

In [6]:
df.head()


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [7]:
df['fuel_type'].nunique()

2

In [8]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [9]:
df[df['origin'] == 'Asia'].sort_values(by = ['fuel_efficiency_mpg'],ascending=False)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
9387                  330            3.0       136.0     1223.298226   
343                   240            2.0         NaN     1652.883753   
7739                  170           10.0       139.0     1491.755825   
9401                  110            1.0       183.0     1707.231276   
5416                  250            6.0       173.0     1354.787120   
...                   ...            ...         ...             ...   
2890                  240            4.0        92.0     4323.711871   
9120                  180            3.0       181.0     4661.144932   
6581                  150            NaN       148.0     4392.759292   
3891                  290            6.0       145.0     4481.764226   
1095                  210            6.0        93.0     4345.732510   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
9387           NaN        2001   Asia  Gasoline  Front-wheel drive        1.0   
343           11.0        2018   Asia  Gasoline  Front-wheel drive        0.0   
7739          13.0        2005   Asia    Diesel  Front-wheel drive        0.0   
9401          11.9        2018   Asia    Diesel    All-wheel drive       -1.0   
5416          17.3        2007   Asia  Gasoline  Front-wheel drive        0.0   
...            ...         ...    ...       ...                ...        ...   
2890          14.8        2007   Asia    Diesel    All-wheel drive       -1.0   
9120          12.5        2004   Asia    Diesel  Front-wheel drive        0.0   
6581          17.1        2016   Asia    Diesel    All-wheel drive        1.0   
3891          17.4        2010   Asia  Gasoline    All-wheel drive        0.0   
1095          18.9        2021   Asia    Diesel    All-wheel drive        0.0   

      fuel_efficiency_mpg  
9387            23.759123  
343             23.204566  
7739            23.033673  
9401            22.919968  
5416            22.858156  
...                   ...  
2890             7.485553  
9120             7.329314  
6581             7.317353  
3891             6.939508  
1095             6.886245  

[3247 rows x 11 columns]

In [10]:
df['horsepower'].median()

149.0

In [11]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [12]:
df['horsepower'].fillna(152.0)

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [13]:
df['horsepower'].median()


149.0

In [24]:
x = df.loc[df['origin'] == 'Asia',['vehicle_weight','model_year']].head(7).values



In [25]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [26]:
xtx = np.dot(x.T , x)

In [27]:
xtx

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [28]:
invert_xtx = np.linalg.inv(xtx)

In [29]:
invert_xtx

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [30]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [31]:
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [32]:
ty = np.dot(invert_xtx,x.T)

In [33]:
ty

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

In [34]:
w = np.dot(ty,y)


In [35]:
w

array([0.01386421, 0.5049067 ])

In [36]:
total_sum = np.sum(w)

In [37]:
total_sum

np.float64(0.5187709081074016)